use secrets in pr

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -15,9 +15,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Build Docker image
-        env:
-          AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
-        run: docker build --build-arg AWS_ACCOUNT=$AWS_ACCOUNT --build-arg BASE_IMAGE=${{ env.IMAGE_NAME }} --build-arg TAG=latest -t ${{ env.IMAGE_NAME }}:latest . >/dev/null 2>&1 || echo "Build Failed"
+        run: docker build --build-arg AWS_ACCOUNT=${{ secrets.AWS_ACCOUNT }} --build-arg BASE_IMAGE=${{ env.IMAGE_NAME }} --build-arg TAG=latest -t ${{ env.IMAGE_NAME }}:latest . -q >/dev/null 2>&1 || echo "Build Failed"
         working-directory: build
 
   test:
